name: Random string action
description: Random a string
inputs:
  input1:
    description: "Input 1"
    required: false
outputs:
  output-1:
    description: "Output 1"
runs:
  using: node14
  main: dist/index.js
