name: 'With actions toolkit action'
description: 'Testing action log'
branding:
  icon: 'message-circle'
  color: 'green'
inputs:
  github-token:
    required: true
    description: 'A github access token'
    default: ${{ github.token }}
  input1:
    description: "Input 1"
    required: false
outputs:
  output1:
    description: "Output 1"
runs:
  using: node12
  main: dist/main/index.js
  post: dist/post/index.js