name: coverage
on:
  pull_request:
    branches:
      - "coverage/**"
    types: [opened, reopened, synchronize]
jobs:
  coverage-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test coverage        
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: yarn
          test-script: yarn jest
