name: pull-request-branches
on:
  pull_request:
    branches:
      - 'pr-branches/**'
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
      - run: echo Hello, today is $TODAY
