name: pull-request-label
on:
  pull_request:
    branches:
      - 'pull-request-label/**'
    types: [opened, labeled, unlabeled]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
      - run: echo Hello, today is $TODAY
