name: random-string
on:
  pull_request:
    branches:
      - "**"
    types: [opened, reopened, synchronize]
jobs:
  random-string:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Random string
        id: xxx      
        uses: ./actions/random-string-action
      - run: |
          echo "TOKEN=${{ steps.xxx.outputs.output1 }}"
          echo "::add-mask::$TOKEN"
        shell: bash
      - run: echo This is my token $TOKEN