name: random-string
on:
  pull_request:
    branches:
      - "**"
    types: [opened, reopened, synchronize]
jobs:
  random-string:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Random string
        id: xxx      
        uses: ./actions/random-string-action
        # shell: bash
      - run: echo TOKEN_X=123abc
      - run: echo "TOKEN=$TOKEN_X" >> $GITHUB_ENV
      - run: echo "::add-mask::$TOKEN"
      - run: echo This is my token $TOKEN