name: random-string
on:
  pull_request:
    branches:
      - "**"
    types: [opened, reopened, synchronize]
jobs:
  random-string:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Random string
        id: xxx      
        uses: ./actions/random-string-action
        # shell: bash
      # - run: echo TOKEN_X=123abc
      #   shell: bash
      # - run: echo "TOKEN=$TOKEN_X" >> $GITHUB_ENV
      #   shell: bash
      # - run: echo "::add-mask::$TOKEN"
      #   shell: bash
      # - run: echo This is my token $TOKEN
      #   shell: bash
      # - run: |
      #     echo "::add-mask::$ABC_TOKEN"
      #     ABC_TOKEN=${{ steps.xxx.outputs.output1 }}
        #  echo "ABC_TOKEN=$the_secret" >> $GITHUB_ENV
        # echo "ABC_TOKEN=${{ steps.xxx.outputs.output1 }}" >> $GITHUB_ENV
      # - run: echo This is my token $ABC_TOKEN
      - run: |
          echo xxx
          ABC_XXX="Mona The Octocat"
        # echo "ABC_XXX=$ABC_XXX" >> $GITHUB_ENV
          echo "::add-mask::$ABC_XXX"
      - run: echo This is my token $ABC_XXX