name: test
on:
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - '**.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn jest
