name: with-actions-toolkit-action
on:
  pull_request:
    branches:
      - "**"
    types: [opened, reopened, synchronize]
jobs:
  trigger-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: trigger with-actions-toolkit-action
        id: xxx
        uses: ./actions/with-actions-toolkit-action
      - run: echo $MY_ENV_1